FROM mcr.microsoft.com/dotnet/core/sdk  AS build-env
WORKDIR /app

# Exibir a versão do SDK do .NET 2.2
RUN dotnet --version

# Copiar sln e restaurar dependencias
COPY . ./
RUN dotnet restore Empresa.Sistema.sln

# Build da aplicacao
COPY . ./
RUN dotnet publish -c Release -o out Empresa.Sistema.sln

# Build da imagem
FROM mcr.microsoft.com/dotnet/core/sdk
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "Empresa.Sistema.Cadastro.API.dll"]