#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app

LABEL version="1.0" maintainer="Carlos_Rodrigues"

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src

COPY . ./
RUN dotnet restore "Empresa.Sistema.sln"

COPY . ./
RUN dotnet build "Empresa.Sistema.sln" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Empresa.Sistema.sln" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Empresa.Sistema.Cadastro.API.dll"]
